- name: install ntp
  package:
    name: ntp
    state: present

- name: deploy ntp conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntp

- name: enable ntp
  service:
    name: ntp
    state: started
    enabled: yes