- name: setup nodesource apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: setup yarn apt key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: setup nodesource repo
  apt_repository:
    repo: "{{ item }} https://deb.nodesource.com/node_14.x {{ ansible_distribution_release }} main"
    state: present
  loop: ['deb', 'deb-src']

- name: setup yarn repo
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present

- name: install python3
  package:
    name:
      - python3
      - python3-pip
    state: present

- name: install hyperglass requirements
  package:
    name:
      - nodejs
      - redis
      - yarn
      - libjpeg-dev
    state: latest

- name: start redis
  service:
    name: redis
    state: started
    enabled: yes

- name: install hyperglass
  pip:
    name: hyperglass
    state: present

- name: install hyperglass service
  template:
    src: hyperglass.service.j2
    dest: /etc/systemd/system/hyperglass.service
  notify: reload systemd
