- name: restart pdns
  service:
    name: pdns
    state: restarted

- name: restart pdns-recursor
  service:
    name: pdns-recursor
    state: restarted

- name: restart dnsdist
  service:
    name: dnsdist
    state: restarted

- name: import powerdns schema
  mysql_db:
    name: powerdns
    state: import
    target: /usr/share/doc/pdns-backend-mysql/schema.mysql.sql
    login_unix_socket: /run/mysqld/mysqld.sock
