- name: install rtorrent
  package:
    name: rtorrent
    state: latest

- name: create rtorrent user
  user:
    name: rtorrent
    shell: /usr/sbin/nologin
    state: present
    home: /etc/rtorrent
    skeleton: /dev/null

- name: create rtorrent session and socket dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: rtorrent
    group: rtorrent
    mode: '0775'
  loop:
    - /etc/rtorrent/session
    - /var/run/rtorrent

- name: create rtorrent log file
  copy:
    dest: /var/log/rtorrent.log
    content: ''
    owner: rtorrent
    force: no

- name: create rtorrent configuration
  template:
    src: rtorrent.rc.j2
    dest: /etc/rtorrent/rtorrent.rc
    owner: rtorrent
  notify: restart rtorrent

- name: create rtorrent service
  template:
    src: rtorrent.service.j2
    dest: /etc/systemd/system/rtorrent.service

- name: start rtorrent
  service:
    name: rtorrent
    state: started
    enabled: yes
