- name: install rpm fusion repositories
  yum:
    name: "{{ item }}"
    disable_gpg_check: yes
    state: present
  loop:
    - "https://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: install kmod-nvidia
  yum:
    name: kmod-nvidia
    state: latest
  notify: reboot

- name: install vaapi/cuda libs
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - libva-vdpau-driver
    - xorg-x11-drv-nvidia-cuda
