- name: setup dnsdist repo
  apt_repository:
    filename: powerdns_dnsdist
    repo: "deb [arch=amd64] http://repo.powerdns.com/debian {{ ansible_distribution_release }}-dnsdist-{{ powerdns.versions.dnsdist | replace('.', '') }} main"
    state: present

- name: install dnsdist
  package:
    name: dnsdist
    state: present

- name: install perl
  package:
    name: perl
    state: present

- name: setup dnsdist conf
  template:
    src: dnsdist.conf.j2
    dest: /etc/dnsdist/dnsdist.conf
  notify: restart dnsdist

- name: start dnsdist
  service:
    name: dnsdist
    state: started
    enabled: yes
