- name: disable tcp slow start after idle
  sysctl:
    name: net.ipv4.tcp_slow_start_after_idle
    value: '0'
    reload: yes

- name: increase max connections
  sysctl:
    name: net.core.somaxconn
    value: '8192'
    reload: yes

- name: swappiness to 10
  sysctl:
    name: vm.swappiness
    value: 10
    reload: yes

- name: allow tcp fast open
  sysctl:
    name: net.ipv4.tcp_fastopen
    value: '3'
    reload: yes

- name: set buffers size
  sysctl:
    name: "{{ item[0] }}"
    value: "{{ item[1] }}"
    reload: yes
  loop:
    - ['net.core.rmem_default', '1048576']
    - ['net.core.rmem_max', '16777216']
    - ['net.core.wmem_default', '1048576']
    - ['net.core.wmem_max', '16777216']
    - ['net.core.optmem_max', '65536']
    - ['net.ipv4.tcp_rmem', '4096 1048576 2097152']
    - ['net.ipv4.tcp_wmem', '4096 65536 16777216']
