
---
- name: systemd reload
  systemd:
    daemon_reload: yes

- name: restart avahi
  service:
    name: avahi-daemon
    state: restarted

- name: restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted
