- name: setup docker apt key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: install docker repo
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: install docker
  package:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: install systemd-sysv
  package:
    name: systemd-sysv
    state: present
    default_release: "{{ ansible_distribution_release }}-backports"

- name: remove sysv
  package:
    name:
      - sysv-rc
      - sysvinit-core
    state: absent
    autoremove: yes

- name: install python3-docker
  package:
    name: python3-docker
    state: present

- name: start docker
  service:
    name: docker
    state: started
    enabled: yes

- name: add zabbix user to docker group
  user:
    name: zabbix
    groups: ['docker']
  notify: restart zabbix-agent

- name: install docker-compose
  package:
    name: docker-compose
    state: present
