- name: download bgpalerter
  get_url:
    url: "https://github.com/nttgin/BGPalerter/releases/download/v{{ bgpalerter.version }}/bgpalerter-linux-x64"
    dest: /usr/local/bin/bgpalerter
    force: yes
    mode: '0755'
  notify: restart bgpalerter

- name: create bgpalerter user
  user:
    name: bgpalerter
    shell: /bin/false
    system: yes
    create_home: no
    home: /var/lib/bgpalerter

- name: create bgpalerter data, conf and log folders
  file:
    path: "{{ item }}"
    state: directory
    owner: bgpalerter
    group: bgpalerter
  loop:
    - /etc/bgpalerter
    - /var/log/bgpalerter
    - /var/lib/bgpalerter

- name: setup prefixes
  template:
    src: prefixes.yml.j2
    dest: /etc/bgpalerter/prefixes.yml
    owner: bgpalerter
    group: bgpalerter
  notify: restart bgpalerter

- name: setup conf
  template:
    src: config.yml.j2
    dest: /etc/bgpalerter/config.yml
    owner: bgpalerter
    group: bgpalerter
  notify: restart bgpalerter

- name: setup service
  template:
    src: bgpalerter.service.j2
    dest: /etc/systemd/system/bgpalerter.service
    owner: bgpalerter
    group: bgpalerter
  notify:
    - reload systemd
    - restart bgpalerter
