- name: setup zfs
  include: zfs.yml
  tags: ['never', 'zfs']

- name: setup samba
  include: samba.yml
  tags: ['never', 'samba']

- name: setup nfs
  include: nfs.yml
  tags: ['never', 'nfs']

- name: setup zrepl
  include: zrepl.yml
  when: zrepl is defined

- name: setup zabbix
  include: zabbix.yml