- name: create data dir
  file:
    path: /data/pdnsadmin
    mode: '0777'
    state: directory

- name: setup pdns-admin docker
  docker_container:
    name: pdns-admin
    image: ngoduykhanh/powerdns-admin:latest
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - /data/pdnsadmin:/data
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
    env:
      OFFLINE_MODE: "False"
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
