- name: disable cockpit banner
  file:
    path: /etc/motd.d/cockpit
    state: absent

- name: disable password login on ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "PasswordAuthentication no"
    regexp: '^PasswordAuthentication'
  notify: restart sshd

- name: disable root login on ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "PermitRootLogin no"
    regexp: '^PermitRootLogin'
  notify: restart sshd
