- name: setup systemd timesyncd conf
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
  notify: restart systemd-timesyncd

- name: start systemd-timesyncd
  service:
    name: systemd-timesyncd
    state: started
    enabled: yes
