- name: install wireguard-tools
  package:
    name: wireguard-tools
    state: latest

- name: enable wireguard
  modprobe:
    name: wireguard
    state: present

- name: enable forwarding
  sysctl:
    name: "{{ item }}"
    value: '1'
  loop: [ 'net.ipv4.ip_forward', 'net.ipv6.conf.all.forwarding' ]

- name: generate wg configuration
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
  notify: restart wg

- name: enable wg0
  systemd:
    name: "wg-quick@wg0"
    enabled: yes
    state: started
